# apps/my-app/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-taiko-client-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/taikoxyz/taiko-helm-charts
    targetRevision: taiko-changes
    path: charts/taiko-client
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
